ops/helmfiles/config/testnet.yaml
=> ci: update rollup-testnet configurations MGX-994

ops/helmfiles/config/testnet.yaml
=> feat: update rollup-testnet nodes to use secret values for Holesky RPC URL MGX-944

ops/helm-charts/rollup-sequencer/templates/deployment.yaml, ops/helm-charts/rollup-updater/templates/deployment.yaml, ops/helmfiles/config/testnet.yaml, rolldown-contract/foundry.toml, rolldown-contract/script/rolldown.s.sol
- **record contract addressed**
- **feat: enable updater and sequencer for rollup-testnet**
- **feat: update used RPC urls to holesky public RPC node**
- **feat: update rollup-testnet nodes to use secret values for Holesky RPC URL**
- **minor configuration tweaks**
=> Public Testnet - contract addresses

avs-aggregator/aggregator.go, avs-aggregator/config.go, avs-aggregator/core/config/flags.go, ops/helmfiles/config/testnet.yaml
use env flag to set debounce timer for easier configuration of service
=> add debounce param cli

rollup-sequencer/src/utils/index.ts
- **fetch only limited number of updates**
- **use helper function to get only range of the updates**
=> [Sequencer] Fetch limited number of requests from L1 contract

compose.yaml, ops/helmfiles/config/frontend.yaml, ops/helmfiles/helmfile.yaml, rollup-sequencer/src/utils/index.ts
- **configuration fixes**
- **make updater wallet seed configurable**
- **Multi L1 frontend env (#147)**
- **feat: update and fix collator dev envs deployment configs to be able to work on all dev envs MGX-1115 (#148)**
- **fix: a few lines missed on merge conflict resolution**
- **alignments**
=> Frontend deployment fixes

stash-dev/app-rollup-dev.yaml
Refactor STASH rollup-dev mangata node value
=> chore: refactor stash rollup_dev mangata node value

stash-dev/.yarnrc.yml, stash-dev/src/repository/ChainRepository.ts, stash-dev/src/server.ts, stash-dev/src/service/SyncBlockService.ts, stash-dev/src/util/Chain.ts, stash-dev/yarn.lock
=> chore: quick fix

stash/src/service/FaucetService.ts
Fee calculation added.
The issue with low fees will still occur from time to time but should be way less often than without any fee calculation (just with automatic one).
=> chore: MGX-1379: calculate fees for the transaction

rollup-sequencer/compose.yml, rollup-sequencer/src/common/constants.ts, rollup-sequencer/src/config/config.ts, rollup-sequencer/src/index.ts, rollup-sequencer/src/utils/index.ts
Introduces new ENV variable for sequencer `WATCHDOG` that sets the watchdog few new block event on both L1 & L2. If for some reason no new block was produced for a longer than `WATCHDOG` parameter value on any of chains, sequencer will shutdown. Watchdog parameter is ignored in case of WATCHDOG  value == 0. When env variable is not set WATCHDOG is not active
=> [MGX-1375][MGX-1336] Watchdog for sequencer

contracts/src/IRolldownPrimitives.sol, contracts/src/Rolldown.sol, contracts/test/rolldown.t.sol
- **fix - add explicit error for range boundries**
- **add 'L2UpdateAccepted' event**
=> add 'L2UpdateAccepted' event

stash/test/api/__snapshots__/coingeko.api.test.ts.snap, stash/test/api/token.stats.api.test.ts
=> chore: fix failing tests of stash (#245)

stash/test/api/token.portfolio.api.test.ts
Covers https://mangatafinance.atlassian.net/browse/GASP-1043
=> Token portfolio tests

contracts/src/Rolldown.sol, contracts/test/rolldown.t.sol, rollup-sequencer/package-lock.json, rollup-sequencer/package.json, rollup-sequencer/src/index.ts, rollup-sequencer/src/utils/index.ts
- **Rolldown.sol - address audit company findings**
- **merkle_root => merkleRoot**
- **sequencer/index.ts - addressing audit comments**
- **sequencer/utils/index.ts - address audit comments**
=> [GASP-1563] Address audit comments

avs-aggregator/aggregator.go, avs-aggregator/op_state_updater.go, avs-finalizer/src/chainio/eigen.rs, avs-finalizer/src/operator.rs, gasp-syncer/src/cli.rs, gasp-syncer/src/syncer.rs
No address change
No behavior change
Addressed some more audit comments and some minor edits
=> Addressed some more audit comments and some minor edits

stash/test/api/deposit.tracing.api.test.ts, stash/test/api/utils.ts, stash/test/api/withdrawal.tracing.api.test.ts
https://mangatafinance.atlassian.net/browse/GASP-1602
adjusted deposit tracing tests to match changes on API and added tests for withdrawal tracing
=> Withdrawal tracing tests

Makefile
- **rust alloy bindings**
- **make command for updating gasp bindings**
=> Automate bindings generation

stash/.gitignore, stash/frontend.enc.env, stash/src/schema/TracingSchema.ts, stash/src/service/FaucetService.ts, stash/src/service/SyncTransactionsService.ts, stash/src/util/ConfigToChain.ts
- Base support added but commented out until we have it deployed on the env (affirmed-network/list will be updated once we enable base on the deployed envrionment)
- Configurable chain per environment added
=> Chore/gasp 1598/base connection and chain configuration per environment

ferry-withdrawal/src/Config.ts, ferry-withdrawal/src/l1/L1Api.ts, ferry-withdrawal/tests/L1Interface.test.ts
- **reproduce bug from testnet**
- **fix for comparing token addresses**
=> [GASP-1708] fix ferry native withdrawals

contracts/script/MultiStage.s.sol, contracts/script/RolldownDeployer.s.sol, contracts/script/RolldownGasUsage.s.sol, contracts/script/input/17000/ethereum_rolldown_output.json, contracts/script/input/421614/arbitrum_gmrs_output.json, contracts/script/input/421614/arbitrum_rolldown_output.json, contracts/script/input/84532/base_gmrs_output.json, contracts/script/input/84532/base_rolldown_output.json, contracts/script/output/17000/ethereum_rolldown_output_upgrade_0.json, contracts/script/output/421614/arbitrum_rolldown_output_upgrade_0.json, contracts/script/output/84532/base_rolldown_output_upgrade_0.json, contracts/src/Rolldown.sol, contracts/test/Rolldown.t.sol, contracts/test/rolldownDeployer.t.sol, scripts/upgrade/upgrade-rolldown-arb-sepolia.sh, scripts/upgrade/upgrade-rolldown-base-sepolia.sh, scripts/upgrade/upgrade-rolldown-eth-holesky.sh
added silent receive function to Rolldown and upgraded testnet v3 rolldown contracts
=> Rolldown receive

stash/src/controller/tokenNetworkPortfolioController.ts
Added to have the same behaviour in trading part and in wallet part for prices.
=> chore: fallback to default history in case no data in the last day

avs-aggregator/rpc_server.go
https://github.com/gasp-xyz/eigensdk-go/pull/5
=> opinfoserv sub retries and rpc isAwaitingRunTrigger endpoint

gasp-node/pallets/rolldown/rpc/src/lib.rs, gasp-node/pallets/rolldown/runtime-api/src/lib.rs, gasp-node/pallets/rolldown/src/lib.rs, gasp-node/pallets/rolldown/src/messages/mod.rs, gasp-node/rollup/node/src/metrics.rs, gasp-node/rollup/runtime/src/lib.rs
- **Feature: Merge `mangata-node` repository code (#411)**
- **[GASP-1099] Provide metrics per chain**
[GASP-1099]: https://mangatafinance.atlassian.net/browse/GASP-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GASP-1099] Prometheus metrics for gasp-node

gasp-node/rollup/node/src/chain_spec.rs, gasp-node/rollup/node/src/command.rs
- introduces dedicated chainspec for holesky
- uses newly created accounts for collator, sequencers and sudo (we used to use public ones, so anyone could use sudo etc)
=> Chainspec - holesky

gasp-node/Cargo.lock, gasp-node/pallets/market/src/lib.rs, gasp-node/rollup/node/Cargo.toml, gasp-node/rollup/runtime/integration-test/src/nontransfer.rs, gasp-node/rollup/runtime/src/lib.rs, gasp-node/rollup/runtime/src/runtime_config.rs
- **Allow crating pools for arbitrage bot**
- **Allow providing liquidity to any pool**
- **change arbitrage account for testing**
=> Pre tradebility release

ferry-withdrawal/src/CloserService.ts, ferry-withdrawal/src/Config.ts, ferry-withdrawal/src/closer.ts, ferry-withdrawal/tests/closer.test.ts
- **paralllel requests processing**
- **introduce start filtering based on id**
=> Closer replicas

gasp-node/Cargo.lock, gasp-node/rollup/runtime/integration-test/Cargo.toml, gasp-node/rollup/runtime/integration-test/src/council.rs, gasp-node/rollup/runtime/integration-test/src/lib.rs, gasp-node/rollup/runtime/src/lib.rs, gasp-node/rollup/runtime/src/runtime_config.rs
Gasp-Node: Council calls by council members are free
=> Gasp-Node: Costless council calls

avs-aggregator/op_state_updater.go
Fixed a bug with the aggregator OpStateUpdater not using the correct block number to getOperatorsFromIds
Fixed a bug where getCurrentOpState was using the wrong input ids
=> fix(aggregator) - getOperatorsFromIds from corrent block

gasp-avs/src/cli.rs, gasp-avs/src/lib.rs, ops/helmfiles/config/holesky-v3.yaml
- **configurable metrics port**
=> feat(gasp-avs): configurable metrics port

gasp-node/moon.yml
We need real test executions and not stop based on test failures.  Already discussed this with Misha
=> Update moon.yml - remove bail on tests 

avs-aggregator/aggregator.go, avs-aggregator/aggregator_test.go, avs-aggregator/core/chainio/avs_reader.go, avs-aggregator/op_state_updater.go, avs-aggregator/types/types.go
Fixed:
https://mangatafinance.atlassian.net/browse/GASP-2116
https://mangatafinance.atlassian.net/browse/GASP-2156
https://mangatafinance.atlassian.net/browse/GASP-2157
=> feat(aggregator): GASP-2116, GASP-2156, GASP-2157

gasp-node/pallets/market/src/lib.rs, gasp-node/pallets/market/src/mock.rs, gasp-node/rollup/runtime/src/lib.rs, gasp-node/rollup/runtime/src/runtime_config.rs
Now atleast 6 planck swap fees will be charged upon swap
=> feat(gasp-node): Multiswap mods fix fees

sequencer/ferry-deposit/src/ferry.rs, sequencer/l2api/src/l2.rs, sequencer/l2api/src/lib.rs, sequencer/l2api/src/mock.rs
- **allow for incompatible bindings **
- **do not consider already ferried deposits**
=> feat: ferry-deposit ignore ferried deposits
